import os
import sys

filepath = sys.argv[1] or input("Input filepath:")
try:
    fileout = sys.argv[2]
except:
    fileout = "out.swd"

endianness = None
#chunkcount = 0
file = open(filepath, "rb")
entirefile = file.read()
file.seek(0, os.SEEK_SET)
def fixbyte(bytee):
    if len(bytee) != 8:
        return ("0"*(8-len(bytee))) + bytee
    else:
        return bytee
nbwavislots = None
nbprgislots = None
wavilen = None
def header(f):
    global nbwavislots
    global nbprgislots
    global wavilen
    global endianness
    
    newstream = bytearray()
    header = bytearray(f.read(4))
    unk18 = bytearray(f.read(4))
    flen = bytearray(f.read(4))
    version = bytearray(f.read(2))
    unk1 = bytearray(f.read(1))
    unk2 = bytearray(f.read(1))
    unk3 = bytearray(f.read(4))
    unk4 = bytearray(f.read(4))
    year = bytearray(f.read(2))
    month = bytearray(f.read(1))
    day = bytearray(f.read(1))
    hour = bytearray(f.read(1))
    minute = bytearray(f.read(1))
    second = bytearray(f.read(1))
    centisecond = bytearray(f.read(1))
    fname = bytearray(f.read(16))
    unk10 = bytearray(f.read(4))
    unk11 = bytearray(f.read(4))
    unk12 = bytearray(f.read(4))
    unk13 = bytearray(f.read(4))
    pcmdlen = bytearray(f.read(4))
    unk14 = bytearray(f.read(2)) # docs mistakenly say 4 bytes
    nbwavislots = bytearray(f.read(2))
    nbprgislots = bytearray(f.read(2))
    unk17 = bytearray(f.read(2))
    wavilen = bytearray(f.read(4))
    
    flen.reverse()
    version.reverse()
    year.reverse()
    unk13.reverse()
    pcmdlen.reverse()
    nbwavislots.reverse()
    nbprgislots.reverse()
    wavilen.reverse()

    if header == bytearray(b"swdb"):
        endianness = "little"
        newstream.extend(bytearray(b"swdl"))
    else:
        endianness = "big"
        newstream.extend(bytearray(b"swdb"))

    newstream.extend(unk18)
    newstream.extend(flen)
    newstream.extend(version)
    newstream.extend(unk1)
    newstream.extend(unk2)
    newstream.extend(unk3)
    newstream.extend(unk4)
    newstream.extend(year)
    newstream.extend(month)
    newstream.extend(day)
    newstream.extend(hour)
    newstream.extend(minute)
    newstream.extend(second)
    newstream.extend(centisecond)
    newstream.extend(fname)
    newstream.extend(unk10)
    newstream.extend(unk11)
    newstream.extend(unk12)
    newstream.extend(unk13)
    newstream.extend(pcmdlen)
    newstream.extend(unk14)
    newstream.extend(nbwavislots)
    newstream.extend(nbprgislots)
    newstream.extend(unk17)
    newstream.extend(wavilen)
    
    with open(fileout, "ab") as writefile:
        writefile.write(newstream)
    writefile.close()
def sampleinfo(f):
    newstream = bytearray()
    print("new sample", f.tell())
    
    
    unk1 = bytearray(f.read(2))
    id = bytearray(f.read(2))
    ftune = bytearray(f.read(1))
    ctune = bytearray(f.read(1))
    rootkey = bytearray(f.read(1))
    ktps = bytearray(f.read(1))
    volume = bytearray(f.read(1))
    pan = bytearray(f.read(1))
    unk5 = bytearray(f.read(1))
    unk58 = bytearray(f.read(1))
    unk6 = bytearray(f.read(2))
    unk7 = bytearray(f.read(2))
    version = bytearray(f.read(2))
    smplfmt = bytearray(f.read(2))
    unk9 = bytearray(f.read(1))
    smplloop = bytearray(f.read(1))
    unk10 = bytearray(f.read(2))
    unk11 = bytearray(f.read(2))
    unk12 = bytearray(f.read(2))
    unk13 = bytearray(f.read(4))
    smplrate = bytearray(f.read(4))
    smplpos = bytearray(f.read(4))
    loopbeg = bytearray(f.read(4))
    looplen = bytearray(f.read(4))
    envon = bytearray(f.read(1))
    envmult = bytearray(f.read(1))
    unk19 = bytearray(f.read(1))
    unk20 = bytearray(f.read(1))
    unk21 = bytearray(f.read(2))
    unk22 = bytearray(f.read(2))
    atkvol = bytearray(f.read(1))
    attack = bytearray(f.read(1))
    decay = bytearray(f.read(1))
    sustain = bytearray(f.read(1))
    hold = bytearray(f.read(1))
    decay2 = bytearray(f.read(1))
    release = bytearray(f.read(1))
    unk57 = bytearray(f.read(1))

    newstream.extend(unk1)
    newstream.extend(id)
    newstream.extend(ftune)
    newstream.extend(ctune)
    newstream.extend(rootkey)
    newstream.extend(ktps)
    newstream.extend(volume)
    newstream.extend(pan)
    newstream.extend(unk5)
    newstream.extend(unk58)
    newstream.extend(unk6)
    newstream.extend(unk7)
    newstream.extend(version)
    newstream.extend(smplfmt)
    newstream.extend(unk9)
    newstream.extend(smplloop)
    newstream.extend(unk10)
    newstream.extend(unk11)
    newstream.extend(unk12)
    newstream.extend(unk13)
    newstream.extend(smplrate)
    newstream.extend(smplpos)
    newstream.extend(loopbeg)
    newstream.extend(looplen)
    newstream.extend(envon)
    newstream.extend(envmult)
    newstream.extend(unk19)
    newstream.extend(unk20)
    newstream.extend(unk21)
    newstream.extend(unk22)
    newstream.extend(atkvol)
    newstream.extend(attack)
    newstream.extend(decay)
    newstream.extend(sustain)
    newstream.extend(hold)
    newstream.extend(decay2)
    newstream.extend(release)
    newstream.extend(unk57)

    #print("wavi unk1", unk1)
    #print("wavi id", id)
    #print("wavi ftune", ftune)
    #print("wavi ctune", ctune)
    #print("wavi rootkey", rootkey)
    #print("wavi ktps", ktps)
    #print("wavi volume", volume)
    #print("wavi pan", pan)
    #print("wavi unk5", unk5)
    #print("wavi unk58", unk58)
    #print("wavi unk6", unk6)
    #print("wavi unk7", unk7)
    #print("wavi version", version)
    print("wavi smplfmt", smplfmt)
    #print("wavi unk9", unk9)
    #print("wavi smplloop", smplloop)
    #print("wavi unk10", unk10)
    #print("wavi unk11", unk11)
    #print("wavi unk12", unk12)
    #print("wavi unk13", unk13)
    print("wavi smplrate", smplrate)
    print("wavi smplpos", smplpos)
    print("wavi loopbeg", loopbeg)
    print("wavi looplen", looplen)
    #print("wavi envon", envon)
    #print("wavi envmult", envmult)
    #print("wavi unk19", unk19)
    #print("wavi unk20", unk20)
    #print("wavi unk21", unk21)
    #print("wavi unk22", unk22)
    #print("wavi atkvol", atkvol)
    #print("wavi attack", attack)
    #print("wavi decay", decay)
    #print("wavi sustain", sustain)
    #print("wavi hold", hold)
    #print("wavi decay2", decay2)
    #print("wavi release", release)
    #print("wavi unk57", unk57)
    
    with open(fileout, "ab") as writefile:
        writefile.write(newstream)
    writefile.close()
def wavi(f):
    newstream = bytearray()
    unk1 = bytearray(f.read(2))
    version = bytearray(f.read(2))
    chunkbeg = bytearray(f.read(4))
    chunklen = bytearray(f.read(4))
    streamcount = 0

    version.reverse()
    chunklen.reverse()

    newstream.extend(unk1)
    newstream.extend(version)
    newstream.extend(chunkbeg)
    newstream.extend(chunklen)

    #print(nbwavislots)
    #print(int.from_bytes(nbwavislots, endianness))
    #print(15 - ((f.tell()+15) % 16))
    for i in range(int.from_bytes(nbwavislots, endianness)):
        pointr = bytearray(f.read(2))
        streamcount = streamcount + 2
        #print("wavi pointr", pointr)
        pointr.reverse()
        newstream.extend(pointr)
    for i in range(15 - ((f.tell()+15) % 16)):
        newstream.extend(f.read(1))
        streamcount = streamcount + 1
    
    with open(fileout, "ab") as writefile:
        writefile.write(newstream)
    writefile.close()

    for i in range(int((int.from_bytes(chunklen, endianness) - streamcount)/64)):
        sampleinfo(f)
def programinfo(f):
    #print("programinfo start")
    newstream = bytearray()
    id = bytearray(f.read(2))
    nbsplits = bytearray(f.read(2))
    prgvol = bytearray(f.read(1))
    prgpan = bytearray(f.read(1))
    unk3 = bytearray(f.read(1))
    thatFbyte = bytearray(f.read(1))
    unk4 = bytearray(f.read(2))
    unk5 = bytearray(f.read(1))
    nblfos = bytearray(f.read(1))
    PadByte = bytearray(f.read(1))
    unk7 = bytearray(f.read(1))
    unk8 = bytearray(f.read(1))
    unk9 = bytearray(f.read(1))

    id.reverse()

    newstream.extend(id)
    newstream.extend(nbsplits)
    newstream.extend(prgvol)
    newstream.extend(prgpan)
    newstream.extend(unk3)
    newstream.extend(thatFbyte)
    newstream.extend(unk4)
    newstream.extend(unk5)
    newstream.extend(nblfos)
    newstream.extend(PadByte)
    newstream.extend(unk7)
    newstream.extend(unk8)
    newstream.extend(unk9)

    #print("id", id)
    #print("nbsplits", nbsplits)
    #print("prgvol", prgvol)
    #print("prgpan", prgpan)
    #print("unk3", unk3)
    #print("thatFbyte", thatFbyte)
    #print("unk4", unk4)
    #print("unk5", unk5)
    #print("nblfos", nblfos)
    #print("PadByte", PadByte)
    #print("unk7", unk7)
    #print("unk8", unk8)
    #print("unk9", unk9)

    #print("lfos start", nblfos)
    for i in range(int.from_bytes(nblfos, "little")):
        #print("new lfo")
        lfo_unk34 = bytearray(f.read(1))
        lfo_unk52 = bytearray(f.read(1))
        lfo_dest = bytearray(f.read(1))
        lfo_wshape = bytearray(f.read(1))
        lfo_rate = bytearray(f.read(2))
        lfo_unk29 = bytearray(f.read(2))
        lfo_depth = bytearray(f.read(2))
        lfo_delay = bytearray(f.read(2))
        lfo_unk32 = bytearray(f.read(2))
        lfo_unk33 = bytearray(f.read(2))

        newstream.extend(lfo_unk34)
        newstream.extend(lfo_unk52)
        newstream.extend(lfo_dest)
        newstream.extend(lfo_wshape)
        newstream.extend(lfo_rate)
        newstream.extend(lfo_unk29)
        newstream.extend(lfo_depth)
        newstream.extend(lfo_delay)
        newstream.extend(lfo_unk32)
        newstream.extend(lfo_unk33)

        #print("lfo_unk34", lfo_unk34)
        #print("lfo_unk52", lfo_unk52)
        #print("lfo_dest", lfo_dest)
        #print("lfo_wshape", lfo_wshape)
        #print("lfo_rate", lfo_rate)
        #print("lfo_unk29", lfo_unk29)
        #print("lfo_depth", lfo_depth)
        #print("lfo_delay", lfo_delay)
        #print("lfo_unk32", lfo_unk32)
        #print("lfo_unk33", lfo_unk33)

    Delimiter = bytearray(f.read(16))
    newstream.extend(Delimiter)

    #print("splits start", nbsplits)
    for i in range(int.from_bytes(nbsplits, "little")):
        #print("new split")
        split_unk10 = bytearray(f.read(1))
        split_id = bytearray(f.read(1))
        split_unk11 = bytearray(f.read(1))
        split_unk25 = bytearray(f.read(1))
        split_lowkey = bytearray(f.read(1))
        split_hikey = bytearray(f.read(1))
        split_lowkey2 = bytearray(f.read(1))
        split_hikey2 = bytearray(f.read(1))
        split_lovel = bytearray(f.read(1))
        split_hivel = bytearray(f.read(1))
        split_lovel2 = bytearray(f.read(1))
        split_hivel2 = bytearray(f.read(1))
        split_unk16 = bytearray(f.read(4))
        split_unk17 = bytearray(f.read(2))
        split_SmplID = bytearray(f.read(2))
        split_ftune = bytearray(f.read(1))
        split_ctune = bytearray(f.read(1))
        split_rootkey = bytearray(f.read(1))
        split_ktps = bytearray(f.read(1))
        split_smplvol = bytearray(f.read(1))
        split_smplpan = bytearray(f.read(1))
        split_kgrpid = bytearray(f.read(1))
        split_unk22 = bytearray(f.read(1))
        split_unk23 = bytearray(f.read(2))
        split_unk24 = bytearray(f.read(2))
        split_envon = bytearray(f.read(1))
        split_enmult = bytearray(f.read(1))
        split_unk37 = bytearray(f.read(1))
        split_unk38 = bytearray(f.read(1))
        split_unk39 = bytearray(f.read(2))
        split_unk40 = bytearray(f.read(2))
        split_atkvol = bytearray(f.read(1))
        split_attack = bytearray(f.read(1))
        split_decay = bytearray(f.read(1))
        split_sustain = bytearray(f.read(1))
        split_hold = bytearray(f.read(1))
        split_decay2 = bytearray(f.read(1))
        split_release = bytearray(f.read(1))
        split_unk53 = bytearray(f.read(1))

        split_SmplID.reverse()


        newstream.extend(split_unk10)
        newstream.extend(split_id)
        newstream.extend(split_unk11)
        newstream.extend(split_unk25)
        newstream.extend(split_lowkey)
        newstream.extend(split_hikey)
        newstream.extend(split_lowkey2)
        newstream.extend(split_hikey2)
        newstream.extend(split_lovel)
        newstream.extend(split_hivel)
        newstream.extend(split_lovel2)
        newstream.extend(split_hivel2)
        newstream.extend(split_unk16)
        newstream.extend(split_unk17)
        newstream.extend(split_SmplID)
        newstream.extend(split_ftune)
        newstream.extend(split_ctune)
        newstream.extend(split_rootkey)
        newstream.extend(split_ktps)
        newstream.extend(split_smplvol)
        newstream.extend(split_smplpan)
        newstream.extend(split_kgrpid)
        newstream.extend(split_unk22)
        newstream.extend(split_unk23)
        newstream.extend(split_unk24)
        newstream.extend(split_envon)
        newstream.extend(split_enmult)
        newstream.extend(split_unk37)
        newstream.extend(split_unk38)
        newstream.extend(split_unk39)
        newstream.extend(split_unk40)
        newstream.extend(split_attack)
        newstream.extend(split_atkvol)
        newstream.extend(split_decay)
        newstream.extend(split_sustain)
        newstream.extend(split_hold)
        newstream.extend(split_decay2)
        newstream.extend(split_release)
        newstream.extend(split_unk53)

        #print("split_unk10", split_unk10)
        #print("split_id", split_id)
        #print("split_unk11", split_unk11)
        #print("split_unk25", split_unk25)
        #print("split_lowkey", split_lowkey)
        #print("split_hikey", split_hikey)
        #print("split_lowkey2", split_lowkey2)
        #print("split_hikey2", split_hikey2)
        #print("split_lovel", split_lovel)
        #print("split_hivel", split_hivel)
        #print("split_lovel2", split_lovel2)
        #print("split_hivel2", split_hivel2)
        #print("split_unk16", split_unk16)
        #print("split_unk17", split_unk17)
        #print("split_SmplID", split_SmplID)
        #print("split_ftune", split_ftune)
        #print("split_ctune", split_ctune)
        #print("split_rootkey", split_rootkey)
        #print("split_ktps", split_ktps)
        #print("split_smplvol", split_smplvol)
        #print("split_smplpan", split_smplpan)
        #print("split_kgrpid", split_kgrpid)
        #print("split_unk22", split_unk22)
        #print("split_unk23", split_unk23)
        #print("split_unk24", split_unk24)
        #print("split_envon", split_envon)
        #print("split_enmult", split_enmult)
        #print("split_unk37", split_unk37)
        #print("split_unk38", split_unk38)
        #print("split_unk39", split_unk39)
        #print("split_unk40", split_unk40)
        #print("split_atkvol", split_attack)
        #print("split_atkvol", split_atkvol)
        #print("split_decay", split_decay)
        #print("split_sustain", split_sustain)
        #print("split_hold", split_hold)
        #print("split_decay2", split_decay2)
        #print("split_release", split_release)
        #print("split_unk53", split_unk53)

    with open(fileout, "ab") as writefile:
        writefile.write(newstream)
    writefile.close()
    retstreamcount = len(newstream)
    return retstreamcount
def prgi(f):
    newstream = bytearray()
    unk1 = bytearray(f.read(2))
    version = bytearray(f.read(2))
    chunkbeg = bytearray(f.read(4))
    chunklen = bytearray(f.read(4))
    streamcount = 0

    version.reverse()
    chunklen.reverse()

    newstream.extend(unk1)
    newstream.extend(version)
    newstream.extend(chunkbeg)
    newstream.extend(chunklen)

    for i in range(int.from_bytes(nbprgislots, endianness)):
        pointr = bytearray(f.read(2))
        streamcount = streamcount + 2
        #print("prgi pointr", pointr)
        pointr.reverse()
        newstream.extend(pointr)
    for i in range(15 - ((f.tell()+15) % 16)):
        newstream.extend(f.read(1))
        streamcount = streamcount + 1
    
    with open(fileout, "ab") as writefile:
        writefile.write(newstream)
    writefile.close()

    while streamcount < int.from_bytes(chunklen, endianness):
        streamcount = streamcount + programinfo(f)
def kgrp(f):
    newstream = bytearray()
    unk1 = bytearray(f.read(2))
    version = bytearray(f.read(2))
    chunkbeg = bytearray(f.read(4))
    chunklen = bytearray(f.read(4))
    streamcount = 0

    version.reverse()
    chunklen.reverse()

    newstream.extend(unk1)
    newstream.extend(version)
    newstream.extend(chunkbeg)
    newstream.extend(chunklen)

    while streamcount < int.from_bytes(chunklen, endianness):
        kgrp_id = bytearray(f.read(2))
        kgrp_poly = bytearray(f.read(1))
        kgrp_priority = bytearray(f.read(1))
        kgrp_vclow = bytearray(f.read(1))
        kgrp_vchigh = bytearray(f.read(1))
        kgrp_unk50 = bytearray(f.read(1))
        kgrp_unk51 = bytearray(f.read(1))

        #print(kgrp_id)

        newstream.extend(kgrp_id)
        newstream.extend(kgrp_poly)
        newstream.extend(kgrp_priority)
        newstream.extend(kgrp_vclow)
        newstream.extend(kgrp_vchigh)
        newstream.extend(kgrp_unk50)
        newstream.extend(kgrp_unk51)
        streamcount = streamcount + 8
    
    for i in range(15 - ((f.tell()+15) % 16)):
        newstream.extend(f.read(1))
        streamcount = streamcount + 1
    with open(fileout, "ab") as writefile:
        writefile.write(newstream)
    writefile.close()
def pcmd(f):
    newstream = bytearray()
    unk1 = bytearray(f.read(2))
    version = bytearray(f.read(2))
    chunkbeg = bytearray(f.read(4))
    chunklen = bytearray(f.read(4))

    version.reverse()
    chunklen.reverse()

    newstream.extend(unk1)
    newstream.extend(version)
    newstream.extend(chunkbeg)
    newstream.extend(chunklen)

    sampledata = f.read(int.from_bytes(chunklen, endianness))
    newstream.extend(sampledata)
    for i in range(15 - ((f.tell()+15) % 16)):
        newstream.extend(f.read(1))
    
    with open(fileout, "ab") as writefile:
        writefile.write(newstream)
    writefile.close()
def eod(f):
    newstream = bytearray()
    unk1 = bytearray(f.read(2))
    version = bytearray(f.read(2))
    chunkbeg = bytearray(f.read(4))
    chunklen = bytearray(f.read(4))

    version.reverse()
    chunklen.reverse()

    newstream.extend(unk1)
    newstream.extend(version)
    newstream.extend(chunkbeg)
    newstream.extend(chunklen)
    
    with open(fileout, "ab") as writefile:
        writefile.write(newstream)
    writefile.close()
    file.close()
    exit()
def examine(f):
    header(f)
    while True:
        newstream = bytearray()

        label = f.read(4)

        newstream.extend(label)

        with open(fileout, "ab") as writefile:
            writefile.write(newstream)
        writefile.close()
        #print(label)
        if label == b"wavi":
            wavi(f)
        elif label == b"prgi":
            prgi(f)
        elif label == b"kgrp":
            kgrp(f)
        elif label == b"pcmd":
            pcmd(f)
        elif label == b"eod\x20":
            eod(f)
        else:
            print("error weird label", label, "at", f.tell())
            exit()
examine(file)
file.close()